### PR TITLE
Added Sameer

### PR DESCRIPTION
**Pull request by Sameer-choudhary-git**

### CODE REVIEW

**Comment by ayushsarode** [comment]
Hey, @Sameer-choudhary-git please don't add extra text, copy the code from the readme file and change the required text as per instructions.

**Comment by Sameer-choudhary-git** [comment]
oh sorry for that @ayushsarode, i have edited it as acco. to instructions.

**Comment by Sameer-choudhary-git** [comment]
@ayushsarode hey sir, my PR got excluded :(
and think its becuase i generated PR before 1 october :(
can i regenerate another pull request pls... <3

**Comment by ayushsarode** [comment]
> generated

you can try but I our PR got excluded and won't count in hacktoberfest

**Comment by Sameer-choudhary-git** [comment]
oh

**Pull request merged**
