### PR TITLE
feat: scroll bottom to top

### LINKED ISSUE #67: Create a Scroll Back To Top Button
As the web app will get longer and longer, create a _**scroll back to top button**_ so that it'll be easy for user to go on the top of the Page

### PR DESCRIPTION
**Pull request by rahulpandey70**
Closes #67 

Added scroll bottom to top

### CODE REVIEW

**Comment by ayushsarode** [comment]
Can you change the color, try circle as black and arrow icon be white

**Comment by rahulpandey70** [comment]
> Can you change the color, try circle as black and arrow icon be white

sure

**Comment by ayushsarode** [comment]
Sorry for inconvenience!

**Comment by ayushsarode** [comment]
> its not looking nice, just reverse the color, arrow should be black and circle be white

**Comment by ayushsarode** [comment]
I'll check it, and merge it today, Thank you!

**Comment by rahulpandey70** [comment]
> Hey @rahulpandey70 there's no significant change as I mentioned that I want circle to be black and arrow to be white
> 
> The button should only become visible as we scroll down the page; it shouldn't be visible when the page is at the top. It should appear once we've scrolled a bit. Screenshot (105)

Ok, I make changes as you asked.

**Comment by ayushsarode** [comment]
Hey, big thanks for your PR on my repo! Even with my many changes, your work stands out. Great job! 🙌

**Pull request merged**
