### PR TITLE
profile added

### PR DESCRIPTION
**Pull request by rahulpandey70**
Profile added

I just added my profile and the rest of the changes are just because of code formatting.

### CODE REVIEW

**Comment by ayushsarode** [comment]
Hey @rahulpandey70, Please make sure you don't change the whole html file, just paste the given code and modify it!
Thank you!

**Comment by rahulpandey70** [comment]
> Hey @rahulpandey70, Please make sure you don't change the whole html file, just paste the given code and modify it! Thank you!

I not changing whole HTML code, As I clicked `ctrl + s` to save file prettier format whole file.

**Comment by rahulpandey70** [comment]
Resolve conflicts, Please have a look

**Comment by ayushsarode** [comment]
Thanks for your contribution!

**Pull request merged**
