### PR TITLE
refactor: Improved title and added design to it.

### PR DESCRIPTION
**Pull request by debuuuu007**
I have changed the title, you can check it out and if you want some change let me know.

If  you do not like the design or have suggestions make sure to mention them.

Resolves issue: #5

### CODE REVIEW

**Comment by ayushsarode** [comment]
> I have changed the title, you can check it out and if you want some change let me know.
> 
> If  you do not like the design or have suggestions make sure to mention them.
> 
> Resolves issue: #5

Looking good, there's one problem, I have merged one PR where there's 2nd profile card, can you add your code with new html file?

**Comment by ayushsarode** [comment]
> I have changed the title, you can check it out and if you want some change let me know.
> 
> If  you do not like the design or have suggestions make sure to mention them.
> 
> Resolves issue: #5

Looking good
I'll merge it soon!

**Comment by debuuuu007** [comment]
Thank you very much for your appreciation, it was my first ever contribution in Open Source. Hope to contribute more to your projects.

**Comment by ayushsarode** [comment]
> Thank you very much for your appreciation, it was my first ever contribution in Open Source. Hope to contribute more to your projects.

Hey @debuuuu007 I'm rebranding the repo, Can you change the title?
Sorry for inconvenience!

**Comment by debuuuu007** [comment]
Yah sure i can definitely do that. Should i make a new PR? Or do changes in this one?

**Comment by debuuuu007** [comment]
I did it you can check and if possible please merge it after 1st october.

**Comment by ayushsarode** [comment]
> I did it you can check and if possible please merge it after 1st october.
> 

Nice!
Actually I have to merge this before 1 October. If you want PR to count in hacktoberfest you can contribute to the repo by making your own profile card
You can check out for steps to do it! 
[contributing.md](https://github.com/ayushsarode/HacktoberFest2023-Profile-Card/blob/main/Contributing.md)

**Pull request merged**
