### PR TITLE
add card

### PR DESCRIPTION
**Pull request by VINAYSH778**
i have modify index.html and add card

### CODE REVIEW

**Comment by ayushsarode** [comment]
_Thank you for your valuable contribution!
Make sure to leave a star ⭐ on repo_

**Comment by VINAYSH778** [comment]
Thank you so much sir this is my first contribution in git

**Comment by ayushsarode** [comment]
> Thank you so much sir this is my first contribution in git 

Always love to help!
You can also share the accomplishment of your first PR being merged on LinkedIn and tag me!
Thank you!

**Comment by VINAYSH778** [comment]
ok sir

**Comment by ayushsarode** [comment]
> ok sir 
> 

You don't have to address me as "sir"; I'm only 18. Please feel free to use my name.

**Comment by VINAYSH778** [comment]
@ayushsarode  thx i just need help to start my open source contribution journey

**Comment by ayushsarode** [comment]
> @ayushsarode thx i just need help to start my open source contribution journey

Glad I help you!

**Comment by VINAYSH778** [comment]
@ayushsarode i did not receive email

**Comment by ayushsarode** [comment]
> @ayushsarode i did not receive email 

For what?

**Comment by VINAYSH778** [comment]
This is my first request but I don't get any response for Marge

**Comment by ayushsarode** [comment]
> This is my first request but I don't get any response for Marge

The PR has been merged, if your GitHub is connected to the email then you'll notify about it. Also make sure to allow GitHub to send mails on your Gmail.

**Comment by VINAYSH778** [comment]
They show same issue

**Pull request merged**
